# Generated by Django 3.1.2 on 2020-10-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CochesVendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('extras_instalados', models.CharField(max_length=100)),
                ('numero_puertas', models.IntegerField()),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientes')),
            ],
        ),
    ]
